server:
 port: 8001
spring:
 application:
  name: microservicecloud-dept
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
  driver-class-name: com.mysql.jdbc.Driver               # mysql驱动包
  url: jdbc:mysql://localhost:3306/clouddb01              # 数据库名称
  username: root
  password: march8th